// <auto-generated />
using System;
using IOMundoConsole.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IOMundoConsole.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230721073445_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IOMundoConsole.Models.Offers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("PersonCombination")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PricePerAdult")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PricePerChild")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ServiceCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ShowStrikePrice")
                        .HasColumnType("bit");

                    b.Property<long>("StayDurationNights")
                        .HasColumnType("bigint");

                    b.Property<decimal>("StrikePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StrikePricePerAdult")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StrikePricePerChild")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("offers");
                });
#pragma warning restore 612, 618
        }
    }
}
